openapi: 3.0.0
info:
  title: API de Juegos Cognitivos
  version: 1.0.0
  description: API REST para la gestión de usuarios y compras de programas cognitivos.

servers:
  - url: https://proyecto1m6-api.onrender.com
  - url: http://localhost:5000/api-docs
    description: Servidor local para desarrollo

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

tags:
  - name: Usuario
  - name: Programa

paths:
  /api/user/register:
    post:
      tags: [Usuario]
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                  example: Juan Pérez
                email:
                  type: string
                  example: juan@example.com
                password:
                  type: string
                  example: secreta123
      responses:
        '201':
          description: Usuario registrado

  /api/user/login:
    post:
      tags: [Usuario]
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  example: juan@example.com
                password:
                  type: string
                  example: secreta123
      responses:
        '200':
          description: Login exitoso

  /api/user/verifytoken:
    get:
      tags: [Usuario]
      summary: Verificar token y obtener perfil
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token válido

  /api/user/update:
    put:
      tags: [Usuario]
      summary: Actualizar usuario autenticado
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Juan Actualizado
                email:
                  type: string
                  example: juan.new@example.com
                password:
                  type: string
                  example: nuevaClave456
      responses:
        '200':
          description: Usuario actualizado

  /api/user/delete:
    delete:
      tags: [Usuario]
      summary: Eliminar cuenta del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Usuario eliminado

  /api/product/create:
    post:
      tags: [Programa]
      summary: Crear nueva compra de programa
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [programType, price]
              properties:
                programType:
                  type: string
                  enum: [basic, standard, premium]
                  example: basic
                price:
                  type: number
                  example: 99.99
      responses:
        '201':
          description: Programa creado

  /api/product/readall:
    get:
      tags: [Programa]
      summary: Obtener todos los programas
      responses:
        '200':
          description: Lista de programas

  /api/product/readone/{id}:
    get:
      tags: [Programa]
      summary: Obtener un programa por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalle del programa

  /api/product/update/{id}:
    put:
      tags: [Programa]
      summary: Actualizar programa (requiere autenticación del dueño)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                programType:
                  type: string
                  example: premium
                price:
                  type: number
                  example: 129.99
      responses:
        '200':
          description: Programa actualizado

  /api/product/delete/{id}:
    delete:
      tags: [Programa]
      summary: Eliminar programa (requiere autenticación del dueño)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Programa eliminado
paths:
  /api/cart:
    get:
      tags:
        - Carrito
      summary: Obtener el carrito del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Carrito obtenido correctamente
        '401':
          description: No autorizado
        '500':
          description: Error del servidor

  /api/cart/add:
    post:
      tags:
        - Carrito
      summary: Agregar un producto al carrito
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - quantity
              properties:
                productId:
                  type: string
                  example: "64e7f3d36d216a2c3be176b9"
                quantity:
                  type: integer
                  example: 2
      responses:
        '200':
          description: Producto agregado correctamente
        '400':
          description: Datos inválidos
        '401':
          description: No autorizado
        '500':
          description: Error del servidor

  /api/cart/remove:
    post:
      tags:
        - Carrito
      summary: Eliminar un producto del carrito
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
              properties:
                productId:
                  type: string
                  example: "64e7f3d36d216a2c3be176b9"
      responses:
        '200':
          description: Producto eliminado correctamente
        '401':
          description: No autorizado
        '404':
          description: Carrito no encontrado
        '500':
          description: Error del servidor

  /api/cart/clear:
    delete:
      tags:
        - Carrito
      summary: Vaciar completamente el carrito del usuario
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Carrito vaciado correctamente
        '401':
          description: No autorizado
        '500':
          description: Error del servidor
    
      /api/checkout:
    post:
      tags:
        - Checkout
      summary: Crear una sesión de pago con Stripe desde el carrito del usuario
      description: Este endpoint genera una sesión de pago en Stripe utilizando los productos del carrito del usuario autenticado.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Sesión de Stripe creada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: https://checkout.stripe.com/pay/cs_test_1234567890abcdef
        '400':
          description: El carrito está vacío o faltan datos
        '401':
          description: No autorizado (token no válido o ausente)
        '500':
          description: Error interno al crear la sesión de pago

